### ISSUE TITLE
Add support for CFW2

### ISSUE THREAD

**Issue by ThePrimalPea** [twinkles-twinstar/TwinStar.ToolKit#10]
**Add ability to decode, unpack or convert CFW2 files and vice versa.**

They were found in PvZ Free
![CFW2](https://user-images.githubusercontent.com/92656767/226383906-0782d7d4-0abd-4391-af36-05f34717811c.png)

**Comment by twinkles-twinstar** [comment]
I'll try to add support for this file in a future release.

**Comment by twinkles-twinstar** [comment]
The new version adds support for encoding and decoding CFW2 files.
