### ISSUE TITLE
WWise Soundbank Decode Error

### ISSUE THREAD

**Issue by Haruma-VN** [twinkles-twinstar/TwinStar.ToolKit#14]
ToolKit cannot decode this BNK, this is official BNK comes from PvZ2-Chinese
Here is the BNK and the original RSG, please check it.
![image](https://github.com/twinkles-twinstar/TwinStar.ToolKit/assets/114157573/ddf5e317-c686-4556-b783-a17a2713cb13)

[bug.zip](https://github.com/twinkles-twinstar/TwinStar.ToolKit/files/12270287/bug.zip)

**Comment by Haruma-VN** [comment]
Although the file is an zlib file, the tool failed in the resource convert for RSB, should be fixed or ignored.

**Comment by twinkles-twinstar** [comment]
There is no problem with toolkit's bnk decoding. The reason for the decoding failure is that the end of the bnk file contains extra null bytes. The bnk decoding function requires that the bnk file has no extra or missing bytes, and the official bnk so far can guarantee this.
This rsg seems to have a problem obviously. The last bnk file is stored in the generic resource data section, but it uses zlib to compress itself independently. Can this bnk file work normally in the game? this rsg file is official or not?

**Comment by twinkles-twinstar** [comment]
The actual size of the bnk is 0x7C00

**Comment by Haruma-VN** [comment]
This file is found in the PvZ2C main.rsb newest version (v3.1.5 I think). It is official RSG extracted from the PvZ2C main.rsb found inside the ipa. Do you need the ipa for more details?

**Comment by twinkles-twinstar** [comment]
At present, it seems that this should be the pvz2c team's mistake... Will this special bnk take effect in the game?
Can you send me that ipa?

**Comment by Haruma-VN** [comment]
Please take it from my Onedrive: https://msconfigs-my.sharepoint.com/:u:/g/personal/harumavn963_365_sfc_edu_vn/EfItqsoOiyVApFcBau5rGlIBdpY2VUdMqyAo58h05x1U1A?e=sgqjzd
