### ISSUE TITLE
Command Forwarder Improvement

### ISSUE THREAD

**Issue by Haruma-VN** [twinkles-twinstar/TwinStar.ToolKit#15]
Command Forwarder should display the output argument, and then check if the file/directory existed. If existed, please ask the user to change or override in the project Helper.
![image](https://github.com/twinkles-twinstar/TwinStar.ToolKit/assets/114157573/4bbdc022-5656-4627-9b8e-80ebdf2e3f88)

**Comment by twinkles-twinstar** [comment]
CommandForwarder can only be responsible for simple parameter forwarding, it will not perform parameter checking, especially if the rules of parameter checking are more complicated, then processing this rule in Helper will make the program more complicated.
Wrong parameters will be re-entered by the user when the shell is running. You can also explicitly enable output parameters in the Helper and specify values.
There is currently no plan to check parameters.
Do you have any other questions? No please close this issue.
