### ISSUE TITLE
Error PopCap (.reanim) file cannot decode 

### ISSUE THREAD

**Issue by Fourzyx** [twinkles-twinstar/TwinStar.ToolKit#19]
![Screenshot_2023-10-29-23-04-47-287_com twinstar toolkit shell_gui](https://github.com/twinkles-twinstar/TwinStar.ToolKit/assets/90524206/3724352c-c676-4c45-9ca8-56ee913c0202)
error decoding .reanim file using toolkit,and how is that possible?

**Comment by twinkles-twinstar** [comment]
Try different version parameters, reanim has four types: desktop-32(for win/mac), mobile-32(for android/iphone), mobile64(for iphone) and television-32(for android-tv).
btw, your shellgui seems to use a different language, what language is it? Can you upload the language file so I can merge it into the project?

**Comment by Fourzyx** [comment]
I translated the language string from shellgui a little, because I don't really understand English when the error occurred.

**Comment by twinkles-twinstar** [comment]
upload your reanim file, i will check them.

**Comment by twinkles-twinstar** [comment]
use `PopCap ZLib Uncompress` method with argument{32} to uncompress to real reanim file, then decode reanim with argument{mobile,32}.
