### ISSUE TITLE
How to use Toolkit for Android?

### ISSUE THREAD

**Issue by Kyant0** [twinkles-twinstar/TwinStar.ToolKit#2]
The document points out you should place some library in /system/lib64, but I am no way to do that as my phone can't mount system partition. Can I use another approach? Why don't you include these libraries in your app directly?

**Comment by Kyant0** [comment]
![Screenshot_20230210-183527_Pixel 启动器](https://user-images.githubusercontent.com/76829190/218080383-c7846b4d-f74b-4cd9-aef5-0ab5046bceac.png)

**Comment by Kyant0** [comment]
Could you give me a working example for the argument?

**Comment by twinkles-twinstar** [comment]
core: /storage/emulated/0/TwinStar/core
script: ?/storage/emulated/0/TwinStar/script/main.js
argument: /storage/emulated/0/TwinStar
