### ISSUE TITLE
Update English

### ISSUE THREAD

**Issue by Haruma-VN** [twinkles-twinstar/TwinStar.ToolKit#20]
Please update the Language for English in Script, I have updated some missing strings that has not been translated to English.

![image](https://github.com/twinkles-twinstar/TwinStar.ToolKit/assets/114157573/600ffe83-6af0-4cc1-8cc7-a9d6e0ae717e)

[English.json](https://github.com/twinkles-twinstar/TwinStar.ToolKit/files/13250650/English.json)

**Comment by twinkles-twinstar** [comment]
merged.
