### ISSUE TITLE
pp.dat was not auto recognized as an rton file

### ISSUE THREAD

**Issue by conflucedd** [twinkles-twinstar/TwinStar.ToolKit#21]
使用Android Shell GUI，对pp.dat进行操作时没有“解码rton”选项，需要手动修改后缀名为rton后才能出现解码选项
建议特殊处理pp.dat

**Comment by twinkles-twinstar** [comment]
以扩展名判断文件类型是工具的预期行为，`dat` 与 `rton` 文件类型不是强关联关系，因此工具不会为 `dat` 文件显示 `rton` 相关功能，不会为 `pp.dat` 做出例外。

如果你需要让工具为 `dat` 文件显示 `rton` 相关功能，请编辑 `<home>/script/Executor/Implement/popcap.reflection_object_notation.js` ，修改其中的 `filter: ['file', /(\.rton)$/i],` 为 `filter: ['file', /(\.rton|\.dat)$/i],` 。
