### ISSUE TITLE
System.IO.IOException Error with helper.msix on Windows 10

### ISSUE THREAD

**Issue by portal-cat** [twinkles-twinstar/TwinStar.ToolKit#22]
Experiencing System.IO.IOException issue relating to incorrect path input with the helper.msix. When running it,  the error as follows occurs:

```
FAILED
System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'C:\Windows\system32\‪T:\TwinStar.ToolKit\kernel'
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at Helper.Module.ModdingWorker.MainPageController.LaunchSession()
```

'C:\Windows\system32\' is awkwardly added at the beginning of the path. This issue is consistent on two different Windows 10 machines.

Also, when I execute "launch.cmd" and input correct "launch_gui.cmd" in the path option, the system does not respond and instead returns to the option for reentering the path.

Any help on these issues would be greatly appreciated.

**Comment by twinkles-twinstar** [comment]
Please send me the helper setting file (`C:\Users\TwinStar\AppData\Local\Packages\TwinStar.ToolKit.Helper_7qfdsg797hj0p\LocalState\Setting.json`).
Try move the TwinStar.ToolKit directory to the C drive.

**Comment by twinkles-twinstar** [comment]
`C:\Windows\system32` is the CWD (current working directory) of the program. When you specify a relative directory, CWD will be automatically added to the path.
Do not use relative paths (such as `./T:/xx`), use absolute paths (such as `T:/xx`)

**Comment by portal-cat** [comment]
> Please send me the helper setting file (`C:\Users\TwinStar\AppData\Local\Packages\TwinStar.ToolKit.Helper_7qfdsg797hj0p\LocalState\Setting.json`). Try move the TwinStar.ToolKit directory to the C drive.

T Drive:
[Setting.json](https://github.com/twinkles-twinstar/TwinStar.ToolKit/files/13510788/Setting.json)
C Drive:
[Setting.json](https://github.com/twinkles-twinstar/TwinStar.ToolKit/files/13519571/Setting.json)

I tried your suggestion but unfortunately, the problem still persists. Even after moving the files to the "C:\Windows\system32\" directory, I keep getting the same error. It seems like the tool is still prepending "C:\Windows\system32" to the correct path.

**Comment by portal-cat** [comment]
Thank you for your assistance, the issue has been resolved. Indeed, it was an easily overlooked detail. It's perplexing as to how the "U+202A character" surfaced, given that I meticulously followed the steps presented in the video tutorial from start to finish.

**Comment by twinkles-twinstar** [comment]
In fact, this is the policy of Windows OS, when you copy the file path from the "file properties" page, U+202A will be added to the beginning of the path.

**Comment by portal-cat** [comment]
> In fact, this is the policy of Windows OS, when you copy the file path from the "file properties" page, U+202A will be added to the beginning of the path.

Hahaha thanks! I'll keep it in my mind to avoid this silly thing happening again
