### ISSUE TITLE
解包 BNK 时要求填写的版本编号是什么意思？

### ISSUE THREAD

**Issue by DRPLANT666** [twinkles-twinstar/TwinStar.ToolKit#23]
有人让我直接输 112，但是请问这到底是什么意思。

**Comment by twinkles-twinstar** [comment]
BNK 有很多版本，不同版本的 BNK 差别可能会非常大，工具需要知晓 BNK 的版本编号才能进行解码与编码。
BNK 的版本编号就是 BNK 文件起始 `0x8` 偏移处的小端 `uint32` 值；出于一些考虑，工具目前不会自动探测版本编号，需要用户手动输入。
PvZ-2 使用过的 BNK 有四个版本：早期为 72 与 88 ，中期为 112 ，10.0 更新后为 140 。
