### ISSUE TITLE
Issue reading UTF8 String on Windows

### ISSUE THREAD

**Issue by Haruma-VN** [twinkles-twinstar/TwinStar.ToolKit#24]
I used a script to obtain list of file, (using KernelX.FileSystem.list_file)
Result is two file starts name with Chinese characters break toolkit (I used Console.success(e, []) to print the file name). Below is the output:
![0cf9254b-ff49-41c7-9f79-53d1a594c70d.png](https://github.com/twinkles-twinstar/TwinStar.ToolKit/assets/114157573/2cfefd80-95fa-46bd-898b-79a01f0e824d)

Actual:

![426308125_903067254651055_5577970099944017666_n.png](https://github.com/twinkles-twinstar/TwinStar.ToolKit/assets/114157573/e4a80a6f-51f5-48d2-99ef-7217e339ba09)

By the way, I'm using Kernel: 62, Script: 103 and ShellCli: 35

**Comment by Haruma-VN** [comment]
Below is the JS if you want to test yourself, you will need to edit the path yourself to test
[test.zip](https://github.com/twinkles-twinstar/TwinStar.ToolKit/files/14209129/test.zip)

**Comment by twinkles-twinstar** [comment]
no error on my device.
![image](https://github.com/twinkles-twinstar/TwinStar.ToolKit/assets/37923060/ff425073-9fd0-48a8-a2cd-028af54d7345)

**Comment by twinkles-twinstar** [comment]
I don't know that both kernel and shellcli use unicode, it seems that this problem should not occur ... Is there an error in the environment of shellgui and helper?

**Comment by Haruma-VN** [comment]
I have tried the ShellGUI and Helper, they worked fine. Only ShellCli occur this issue on my machine.

**Comment by twinkles-twinstar** [comment]
Will this error occur when the language of the toolkit is changed to Chinese?

**Comment by Haruma-VN** [comment]
This error still occur in ShellCLI even when change the language to Chinese. By the way, the output of Chinese string in los still normal.

**Comment by twinkles-twinstar** [comment]
try this test:
`Kernel\kernel\utility\file_system\file_system.hpp:315`
```cpp
for (auto & entry : std::filesystem::directory_iterator{make_std_path(target)}) {
					auto name = make_string(self_cast<std::string>(entry.path().filename().generic_u8string()));
					M_log(mss(Range::accumulate(name, [](auto & e) { return "{:02X} "_sf(e); }, ""_s))); // insert this line
```
then, call KernelX.FileSystem.list, view the byte data in the output window.

**Comment by Haruma-VN** [comment]
For some reason when messing with the settings.json, my terminal turned back to normal and the Kernel became fine when obtaining path (very strange). But it is not caused from the toolkit, so i will probably close this issue as completed.

![Messenger_creation_9caf786d-71fd-4997-b6de-b0a0be65bd49.jpeg](https://github.com/twinkles-twinstar/TwinStar.ToolKit/assets/114157573/388a3f21-ea71-4e49-8210-70d9de3ec729)
