### ISSUE TITLE
Helper: Animation Viewer problem

### ISSUE THREAD

**Issue by Haruma-VN** [twinkles-twinstar/TwinStar.ToolKit#25]
The Helper is extremely strict in JSON parsing, yet also animation rendering. Even the pam json made by toolkit is refused, can it be fixed? When an exception is thrown, the helper itself refused to open a new file (please fix this, second image)
Below is the pam json
![image](https://github.com/twinkles-twinstar/TwinStar.ToolKit/assets/114157573/8b4616e2-b81f-482e-93e8-a3b826645906)

![image](https://github.com/twinkles-twinstar/TwinStar.ToolKit/assets/114157573/6ca99ac9-00df-4589-b8ee-7d243ee2cb75)
[CHILLYPEPPER.pam.json](https://github.com/twinkles-twinstar/TwinStar.ToolKit/files/14232736/CHILLYPEPPER.pam.json)

**Comment by twinkles-twinstar** [comment]
This pam is wrong, it is trying to delete a non-existent layer (index 43). Is this json generated by a tool? Has it been modified?

**Comment by Haruma-VN** [comment]
I modified it for some experimental. Can the Helper be modified: if the current pam json is broken, it allows to select or ask the user to select other pam json rather than block the users do anything?

**Comment by twinkles-twinstar** [comment]
Regardless of whether pam has errors, you can clear or reselect pam.
