### ISSUE TITLE
Bug: PopCap Animation JSON Convert to Flash

### ISSUE THREAD

**Issue by CreatorHusky** [twinkles-twinstar/TwinStar.ToolKit#27]
The sizes and positions of the sprites has some problems.
<img width="553" alt="屏幕截图 2024-02-17 170456" src="https://github.com/twinkles-twinstar/TwinStar.ToolKit/assets/90967545/f00bf168-072f-4e6f-a6af-924f3cac9002">

**Comment by Haruma-VN** [comment]
You need to use Flash Animation resize function to change the position.

**Comment by CreatorHusky** [comment]
> You need to use Flash Animation resize function to change the position.

Thank you, I've solved the problem with your help.

**Comment by CreatorHusky** [comment]
a

**Comment by ValentyneMu** [comment]
> You need to use Flash Animation resize function to change the position.

Thanks for your help! If it hadn't been for you I would never have known, thank you!
