### ISSUE TITLE
Bug: Export of PAMs to Flash is misshaped!

### ISSUE THREAD

**Issue by ValentyneMu** [twinkles-twinstar/TwinStar.ToolKit#28]
I just tried your new tool and it's magnificent!!! Shows the animations perfectly in the "Helper". But the same results are not shown when exporting to XFL (Flash). I tried with RSBs for ipad3, ipad2; also with an Android OBB and readjusting Atlas or not. With Adobe Flash CS6 and Animate CC 2019 and obviously placing each sprite in the "\LIBRARY\media" path of each plant folder, but the animations still look like a mess (even through my locale is correctly set) :(

The thing is, with Animate it's the only way to export them to .MP4 or another video format, as well as a .GIF or a transparent image like .PNG. I can't capture the screen either because it records very laggy. Or else you could add to the "Helper" the option to export animations both in .PNG and in any HQ video format and also be able to change the background color.

I wouldn't have any more problems for now. Otherwise your tool is amazing, it shows the effort you put into it. Thank you very much for it and keep up the good work!

![BL](https://github.com/twinkles-twinstar/TwinStar.ToolKit/assets/49624756/267e6ed5-e80b-4890-acf2-41b85d220ee7)
![EP](https://github.com/twinkles-twinstar/TwinStar.ToolKit/assets/49624756/8dcee3e2-a97e-414c-9ef4-3fcd19771750)
![BD](https://github.com/twinkles-twinstar/TwinStar.ToolKit/assets/49624756/49982a77-95b7-40a3-9548-d83e7b10e886)
![BD2](https://github.com/twinkles-twinstar/TwinStar.ToolKit/assets/49624756/319c865e-7747-467c-892f-29328b8e6b0b)
![TT](https://github.com/twinkles-twinstar/TwinStar.ToolKit/assets/49624756/17f5abe5-e2c2-4871-a1e7-1db144cd15ea)

**Comment by CreatorHusky** [comment]
Using "Flash Resize image" can solve the problem.
The Image resolution could be 1536 or 768.
