### ISSUE TITLE
JSON Trailing Commas

### ISSUE THREAD

**Issue by MrNooberDude** [twinkles-twinstar/TwinStar.ToolKit#29]
When decoding RTONs and NEWTONs into JSON, almost everything has a comma at the end.

Example (Resources.NEWTON):
![image](https://github.com/twinkles-twinstar/TwinStar.ToolKit/assets/67441866/0d6529f0-f5a4-4014-bc56-1c140f7bce3b)

**Comment by twinkles-twinstar** [comment]
trailing comma is default setting, you can turn off, see [document](https://github.com/twinkles-twinstar/TwinStar.ToolKit.Document/blob/master/english/question.md#JSON-file-format)
