### ISSUE TITLE
Shell GUI Error

### ISSUE THREAD

**Issue by Tre-VN** [twinkles-twinstar/TwinStar.ToolKit#3]
Hi apparently your shell GUI denied access to the directory in the phone, is there anyway I can allow it without root? Thanks 👍
![Screenshot_20230215-210614.jpg](https://user-images.githubusercontent.com/114157573/219049397-35130e6f-f0b2-469d-873a-040f8d74ada2.jpg)

**Comment by twinkles-twinstar** [comment]
You need to give ShellGUI full read and write permissions for external storage in the system settings

**Comment by Tre-VN** [comment]
Thank you, it worked! I wonder if you could translate the whole tool to English next version.
![Screenshot_20230215-214644.jpg](https://user-images.githubusercontent.com/114157573/219060852-712ecfcd-c6f7-4039-aeda-095c19aa7b6f.jpg)
