### ISSUE TITLE
Bug on Assistant

### ISSUE THREAD

**Issue by Haruma-VN** [twinkles-twinstar/TwinStar.ToolKit#31]
When I click Modding Worker title on navbar and click menu, the exception is thrown. Can it be fixed? 
![Screenshot_2024-05-13-16-00-28-084_com.twinstar.toolkit.assistant.jpg](https://github.com/twinkles-twinstar/TwinStar.ToolKit/assets/114157573/9054ad80-0d70-4ce1-8583-f32c6dd4cbf6)

**Comment by twinkles-twinstar** [comment]
This is because you used the drag gesture on the appbar on the mobile platform, which caused the DragToMoveArea component to report an error.
I'll fix it in the next update.

**Comment by twinkles-twinstar** [comment]
fixed.
