### ISSUE TITLE
Unpack RSB Bug

### ISSUE THREAD

**Issue by Tre-VN** [twinkles-twinstar/TwinStar.ToolKit#6]
After drag "RSBRepair.js" to TwinStar, use execute JS and apply the changes to the RSB, the tool still failed to unpack this RSB.
Can you check it? 
Here is the RSB: https://drive.google.com/file/d/1TukHfBcftROW_bhzhBSH1-cjuf-5D__6/view?usp=sharing

![image](https://user-images.githubusercontent.com/114157573/219876545-3083d309-a05e-457e-9705-c3341dd56b25.png)

**Comment by Tre-VN** [comment]
Here is the proof after executing "RepairRSBPopCap.js"
![image](https://user-images.githubusercontent.com/114157573/219876690-a17d329b-124e-483e-9840-5dc219a50fbb.png)
![image](https://user-images.githubusercontent.com/114157573/219876704-8de36e9b-8905-42c9-a2f3-d20ba78f8bd6.png)

**Comment by twinkles-twinstar** [comment]
This error is caused by an etc1-ptx in rsb not being filled to a 2^n square, perhaps the unpacking logic really needs to be changed. If the game allows non-square etc1 textures, some logic in the script will also need to be changed. I don't have time to fix this issue at the moment, please keep the issue open.

**Comment by Tre-VN** [comment]
I kinda want the RSB being similar to PopCap's RSB. Can you make the RepairPopcapRSB.js delete all comments in the rsb and rsgp header?

**Comment by twinkles-twinstar** [comment]
The current version update has fixed the RSB unpacking logic error related to this issue, but this fix will not allow your RSB to be unpacked, because there is a logic error in the RSB, you need to use the new version of the RepairPopcapRSB script to repair the RSB.

**Comment by twinkles-twinstar** [comment]
> I kinda want the RSB being similar to PopCap's RSB. Can you make the RepairPopcapRSB.js delete all comments in the rsb and rsgp header?
This is meaningless, the purpose of the repair script is to allow disturbed packets to be unpacked, nothing more.

**Comment by twinkles-twinstar** [comment]
> The current version update has fixed the RSB unpacking logic error related to this issue, but this fix will not allow your RSB to be unpacked, because there is a logic error in the RSB, you need to use the new version of the RepairPopcapRSB script to repair the RSB.

There is no error in the data package. I made a wrong judgment before, and the error update introduced by it has been fixed in the new version.
