### ISSUE TITLE
这是怎么了

### ISSUE THREAD

**Issue by nmslq** [twinkles-twinstar/TwinStar.ToolKit#7]
![Screenshot_2023-02-28-20-09-07-599_com twinstar toolkit shell_gui](https://user-images.githubusercontent.com/96362104/221850825-531361d7-ea0a-47e2-9cfd-30f5f61e0ebc.jpg)
今天更新了新版本,就发生了这个

**Comment by twinkles-twinstar** [comment]
重新编译后的core已经分发至release，更新后即可解决这一问题。确认解决后请关闭本issue。
