### ISSUE TITLE
How to use TwinStar.Toolkit to extract resource data for TwinStar.Helper?

### ISSUE THREAD

**Issue by Haruma-VN** [twinkles-twinstar/TwinStar.ToolKit#8]
You said it can "directly provide RSB unpacking + resource conversion functions to decode all PAMs in the data packet and generate an exploded view.". How can I use it on the toolkit, it currently only popup these things.
![image](https://user-images.githubusercontent.com/114157573/222627413-79b33bf1-f616-422d-a369-ba0c3195bf2e.png)

**Comment by twinkles-twinstar** [comment]
This is a typo.
You need to use RSB Unpack (resource mode) first
Then use RSB Resoucre convert (with .rsb.bundle as input)

**Comment by Haruma-VN** [comment]
Sorry to disturb you, I extracted as 3, resource mode, but the tool does not responding with the .rsb.bundle I asserted to the tool, I am extracting pvz2 10.4.1 rsb by the way.

![image](https://user-images.githubusercontent.com/114157573/222632341-bd955738-9ad0-40c0-a15d-3b89f911d11f.png)

![image](https://user-images.githubusercontent.com/114157573/222632297-7c5b5bf5-87b6-4542-a080-38771e4b43fd.png)

![image](https://user-images.githubusercontent.com/114157573/222632490-f6d1d62d-51ea-4db9-9191-1f6cf39d905d.png)

**Comment by twinkles-twinstar** [comment]
You have to let the tool output the resource file (export resource = y)

**Comment by Haruma-VN** [comment]
after that, the tool actually said extracting resource manifest, but it said that it is not a function

![image](https://user-images.githubusercontent.com/114157573/222632975-01bb1347-8027-47ef-90a3-84b6dac8009b.png)

**Comment by twinkles-twinstar** [comment]
Due to the differences between the 10.4 resources.json and the old version, the current script cannot correctly handle the 10.4 resources.json. I will adapt it later, please wait for the script to be updated.

**Comment by twinkles-twinstar** [comment]
The new version of script has fixed this problem, please try again after updating, then close this issue after it is correct

**Comment by Haruma-VN** [comment]
Thanks, it works!
