### ISSUE TITLE
手机能解码wwise-encoded_media吗

### ISSUE THREAD

**Issue by nmslq** [twinkles-twinstar/TwinStar.ToolKit#9]

**Comment by twinkles-twinstar** [comment]
解码WEM需要外部程序 ffmpeg 与 ww2ogg ，如果你需要在安卓或iOS设备上解码 WEM ，需要先自行构建这两个程序面向安卓或iOS的可执行程序，再按文档所言放置于主目录内，此二者都是开源项目。

**Comment by nmslq** [comment]
好

**Comment by nmslq** [comment]
是两个程序都需要吗

**Comment by twinkles-twinstar** [comment]
ffmpeg必须，ww2ogg只在解码vorbis编码的WEM时会用到，不过脚本层面会检测指定的ww2ogg程序和pcb文件路径是否存在，你可以随便设成其他文件的路径绕过脚本的检测。
